import { useEffect } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import useLogin from "../hooks/useLogin";
import Dashboard from "../components/Dashboard";

const Home: NextPage = () => {
  const { handleIsLogged } = useLogin();

  useEffect(() => {
    handleIsLogged();
  }, [handleIsLogged]);

  return (
    <div>
      <Head>
        <title>PCBuilder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Dashboard />
    </div>
  );
};

export default Home;
