import type { NextPage } from "next";
import { useEffect } from "react";
import Head from "next/head";
import About from "../components/About";
import Dashboard from "../components/Dashboard";
import useLogin from "../hooks/useLogin";
import { useAppSelector } from "../redux/hook";

const Home: NextPage = () => {
  const { loggedIn } = useAppSelector((state) => state.auth);

  const { handleLoadUser } = useLogin();

  useEffect(() => {
    handleLoadUser();
  }, [handleLoadUser]);

  return (
    <div>
      <Head>
        <title>PCBuilder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {loggedIn ? <Dashboard /> : <About />}
    </div>
  );
};

export default Home;
